### ISSUE TITLE
IntAct

### ISSUE THREAD

**Issue by sophiakrix** [bio2bel/bio2bel#30]
Mapping from IntAct interaction types to BEL

**Comment by sophiakrix** [comment]
I am querying right now a database to receive the data from IntAct. I suppose for bio2bel it is necessary to retrieve the file directly from the IntAct website?

**Comment by cthoyt** [comment]
Yes a Bio2BEL script should also take care of downloading the data. You can see the other scripts as examples, but the most useful function is

```python
from bio2bel.utils import ensure_path
MODULE_NAME = 'intact'
URL = '...'
path = ensure_path(MODULE_NAME, URL)
```

this function takes are of downloading the file and placing it in the bio2bel directory.

**Comment by sophiakrix** [comment]
- [ ] download data

- [ ] understand headers

- [ ] add triples to BEL graph

**Comment by sophiakrix** [comment]
I'm unable to push from my own local branch to bio2bel currently. Could you give me permission please?

**Comment by cthoyt** [comment]
nope. make a fork

**Comment by cthoyt** [comment]
Read this: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by cthoyt** [comment]
Or this: https://reflectoring.io/github-fork-and-pull/

**Comment by sophiakrix** [comment]
Is there a function in bio2bel to download and unzip files?

**Comment by cthoyt** [comment]
Not specifically but after you ensure the path, you can use the zipfile
built in library to get the data out programmatically (you won’t even need
to actually unzip it, then you can load from pandas)

If the zip is just a file and not a folder, pandas can handle it directly

**Comment by sophiakrix** [comment]
I have the path with ensure_path and then did

df = pd.read_csv(path, sep=SEP, compression='zip'),

but it still gives me an error:

zipfile.BadZipFile: File is not a zip file

**Comment by cthoyt** [comment]
what do you see when you unzip the folder? is it a single file, or does it give a folder?

**Comment by cthoyt** [comment]
anyway make the PR and we make commets directly on the code, I don't want to talk about this abstractly anymore

**Comment by sophiakrix** [comment]
> what do you see when you unzip the folder? is it a single file, or does it give a folder?

It's a single file, intact.zip

**Comment by sophiakrix** [comment]
In here I've loaded the file and put it into a pandas dataframe:

https://github.com/sophiakrix/bio2bel/blob/master/src/bio2bel/sources/intact.py

but the issue with the zip file still exists.
