### ISSUE TITLE
Pathway Commons

### ISSUE THREAD

**Issue by sophiakrix** [bio2bel/bio2bel#32]
Mapping from interaction types in Pathway Commons to BEL

**Comment by cthoyt** [comment]
Hard no. Please read the Bio2BEL paper for reasoning on why we won't convert Pathway Commons to BEL - in short, they make lots of opaque assumptions, throw away high granularity information, and ultimately aren't easy to deal with. It's better to get the data that they use directly from the source, many of which are already available in Bio2BEL.

**Comment by cthoyt** [comment]
Which parts of Pathway Commons did you actually want? If you didn't have something in mind then it would be best to think about the actual problem you're interested in solving

**Comment by sophiakrix** [comment]
Allright, then I won't map pathway commons here. What I am interested in is basically summarising the interaction types between biological objects in as few edge types as possible. This is why in my case, it is not such a dilemma that pathway commons does not differentiate types of interaction in such a high granularity. But I can see that this poses a problem for this application.

**Comment by cthoyt** [comment]
Okay. If you're just looking for a big graph with lots of relations, you can alternatively use [OpenBioLink](https://github.com/openbiolink/openbiolink#biological-expression-language-bel-writer) (you'll need to run the script described here) or [Hetionet](https://github.com/pybel/hetionet-bel) (available for direct download)

**Comment by sophiakrix** [comment]
Ok, great. Thank you!
