### ISSUE TITLE
Blender Knowledge Graph

### ISSUE THREAD

**Issue by cthoyt** [bio2bel/bio2bel#47]
@djinnome is looking into this

http://159.89.180.81/demo/covid/KG.zip

**Comment by djinnome** [comment]
Would you be willing to  create a Blender repository under bio2bel for which I can contribute and add members?
Should I use cookie cutter to set up the structure, or should I just copy something like bio2bel/phosphosite's structure?

**Comment by cthoyt** [comment]
Actually the new style is just to add a new module or sub package in bio2bel.sources. The whole “multiple repository” thing wasn’t such a good idea after all. However, the concept of plugins still is alive!

**Comment by djinnome** [comment]
OK, below is the full set of Blender relationships. My goal is to convert each type to a BEL statement:

* +1 = Activation like relation</p>
* -1 = Inhibition like relation</p>
*  0 = Impacts "valid activation pathway" in an unspecified or non-monotonic way</p>

<table>
  <colgroup>
    <col/>
    <col/>
    <col/>
  </colgroup>
  <tbody>
    <tr>
      <td>
        <strong>edge_type VARCHAR</strong>
      </td>
      <td>
        <strong>Count</strong>
      </td>
      <td>
        <strong>Activation Relation (+1/0/-1)</strong>
      </td>
    </tr>
    <tr>
      <td>increases^expression</td>
      <td>802174</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^expression</td>
      <td>583141</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>affects^cotreatment</td>
      <td>355090</td>
      <td>0</td>
    </tr>
    <tr>
      <td>decreases^reaction</td>
      <td>269134</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>affects^expression</td>
      <td>169004</td>
      <td>1</td>
    </tr>
    <tr>
      <td>Activation</td>
      <td>168576</td>
      <td>1</td>
    </tr>
    <tr>
      <td>Inhibition</td>
      <td>114234</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>increases^reaction</td>
      <td>76201</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^binding</td>
      <td>71595</td>
      <td>0</td>
    </tr>
    <tr>
      <td>increases^activity</td>
      <td>68685</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^phosphorylation</td>
      <td>40557</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^activity</td>
      <td>39663</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>affects^reaction</td>
      <td>39171</td>
      <td>1</td>
    </tr>
    <tr>
      <td>IncreaseAmount</td>
      <td>35940</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^methylation</td>
      <td>35838</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^abundance</td>
      <td>27247</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^methylation</td>
      <td>25936</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>DecreaseAmount</td>
      <td>22705</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>increases^secretion</td>
      <td>21673</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^response to substance</td>
      <td>18751</td>
      <td>0</td>
    </tr>
    <tr>
      <td>affects^methylation</td>
      <td>13852</td>
      <td>0</td>
    </tr>
    <tr>
      <td>increases^response to substance</td>
      <td>13069</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^cleavage</td>
      <td>12183</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^localization</td>
      <td>10947</td>
      <td>0</td>
    </tr>
    <tr>
      <td>decreases^response to substance</td>
      <td>9663</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^phosphorylation</td>
      <td>9336</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>Phosphorylation</td>
      <td>7069</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^metabolic processing</td>
      <td>6072</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^chemical synthesis</td>
      <td>5620</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^uptake</td>
      <td>5303</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^splicing</td>
      <td>4218</td>
      <td>0</td>
    </tr>
    <tr>
      <td>increases^transport</td>
      <td>3714</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^degradation</td>
      <td>3407</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^activity</td>
      <td>3210</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^secretion</td>
      <td>3114</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>increases^O-linked glycosylation</td>
      <td>3007</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^oxidation</td>
      <td>2879</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^abundance</td>
      <td>2432</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>affects^metabolic processing</td>
      <td>2367</td>
      <td>0</td>
    </tr>
    <tr>
      <td>Dephosphorylation</td>
      <td>2317</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>increases^localization</td>
      <td>2085</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^mutagenesis</td>
      <td>1897</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^reduction</td>
      <td>1702</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^abundance</td>
      <td>1647</td>
      <td>0</td>
    </tr>
    <tr>
      <td>increases^acetylation</td>
      <td>1232</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^sumoylation</td>
      <td>1196</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^phosphorylation</td>
      <td>1188</td>
      <td>0</td>
    </tr>
    <tr>
      <td>increases^glucuronidation</td>
      <td>1116</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^transport</td>
      <td>1082</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^hydroxylation</td>
      <td>1006</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^export</td>
      <td>970</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^hydrolysis</td>
      <td>949</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^secretion</td>
      <td>898</td>
      <td>0</td>
    </tr>
    <tr>
      <td>Ubiquitination</td>
      <td>893</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^import</td>
      <td>862</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^stability</td>
      <td>764</td>
      <td>1</td>
    </tr>
    <tr>
      <td>Methylation</td>
      <td>740</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^folding</td>
      <td>709</td>
      <td>0</td>
    </tr>
    <tr>
      <td>decreases^chemical synthesis</td>
      <td>552</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^uptake</td>
      <td>542</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^metabolic processing</td>
      <td>517</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^degradation</td>
      <td>502</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^sumoylation</td>
      <td>491</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>Demethylation</td>
      <td>469</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>increases^ubiquitination</td>
      <td>452</td>
      <td>1</td>
    </tr>
    <tr>
      <td>Acetylation</td>
      <td>406</td>
      <td>1</td>
    </tr>
    <tr>
      <td>Deubiquitination</td>
      <td>388</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^cleavage</td>
      <td>347</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^localization</td>
      <td>346</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>increases^sulfation</td>
      <td>334</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^acetylation</td>
      <td>312</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>affects^chemical synthesis</td>
      <td>297</td>
      <td>0</td>
    </tr>
    <tr>
      <td>increases^glutathionylation</td>
      <td>296</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^transport</td>
      <td>290</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>increases^ADP-ribosylation</td>
      <td>280</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^export</td>
      <td>259</td>
      <td>0</td>
    </tr>
    <tr>
      <td>decreases^stability</td>
      <td>233</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>affects^acetylation</td>
      <td>227</td>
      <td>0</td>
    </tr>
    <tr>
      <td>affects^uptake</td>
      <td>222</td>
      <td>0</td>
    </tr>
    <tr>
      <td>decreases^export</td>
      <td>195</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>Glycosylation</td>
      <td>187</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^cleavage</td>
      <td>182</td>
      <td>0</td>
    </tr>
    <tr>
      <td>increases^splicing</td>
      <td>177</td>
      <td>1</td>
    </tr>
    <tr>
      <td>Hydroxylation</td>
      <td>167</td>
      <td>1</td>
    </tr>
    <tr>
      <td>Deacetylation</td>
      <td>140</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>affects^reduction</td>
      <td>139</td>
      <td>0</td>
    </tr>
    <tr>
      <td>decreases^ubiquitination</td>
      <td>129</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>Ribosylation</td>
      <td>128</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^oxidation</td>
      <td>115</td>
      <td>0</td>
    </tr>
    <tr>
      <td>increases^nitrosation</td>
      <td>115</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^lipidation</td>
      <td>112</td>
      <td>1</td>
    </tr>
    <tr>
      <td>Sumoylation</td>
      <td>108</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^ADP-ribosylation</td>
      <td>84</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^oxidation</td>
      <td>78</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^import</td>
      <td>74</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^hydroxylation</td>
      <td>68</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>increases^alkylation</td>
      <td>63</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^reduction</td>
      <td>61</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>Deglycosylation</td>
      <td>58</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>affects^sumoylation</td>
      <td>57</td>
      <td>0</td>
    </tr>
    <tr>
      <td>decreases^amination</td>
      <td>50</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^prenylation</td>
      <td>50</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>affects^glucuronidation</td>
      <td>46</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^sulfation</td>
      <td>44</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^degradation</td>
      <td>44</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^import</td>
      <td>43</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^hydrolysis</td>
      <td>42</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^hydroxylation</td>
      <td>42</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^alkylation</td>
      <td>41</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^nitrosation</td>
      <td>41</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>increases^glycosylation</td>
      <td>39</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^ethylation</td>
      <td>35</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^sulfation</td>
      <td>35</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>Desumoylation</td>
      <td>30</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^folding</td>
      <td>29</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^geranoylation</td>
      <td>28</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>increases^acylation</td>
      <td>28</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^glucuronidation</td>
      <td>28</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^hydrolysis</td>
      <td>28</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>affects^mutagenesis</td>
      <td>27</td>
      <td>0</td>
    </tr>
    <tr>
      <td>affects^stability</td>
      <td>27</td>
      <td>0</td>
    </tr>
    <tr>
      <td>affects^ubiquitination</td>
      <td>27</td>
      <td>0</td>
    </tr>
    <tr>
      <td>increases^carboxylation</td>
      <td>26</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^glycosylation</td>
      <td>26</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>Palmitoylation</td>
      <td>24</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^farnesylation</td>
      <td>21</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^lipidation</td>
      <td>20</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^glutathionylation</td>
      <td>20</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>increases^carbamoylation</td>
      <td>19</td>
      <td>1</td>
    </tr>
    <tr>
      <td>Deribosylation</td>
      <td>19</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^carboxylation</td>
      <td>16</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>increases^prenylation</td>
      <td>15</td>
      <td>1</td>
    </tr>
    <tr>
      <td>Dehydroxylation</td>
      <td>15</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>increases^glycation</td>
      <td>14</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^folding</td>
      <td>14</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^splicing</td>
      <td>12</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>affects^glycosylation</td>
      <td>10</td>
      <td>0</td>
    </tr>
    <tr>
      <td>increases^N-linked glycosylation</td>
      <td>9</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^amination</td>
      <td>7</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^farnesylation</td>
      <td>6</td>
      <td>1</td>
    </tr>
    <tr>
      <td>increases^ribosylation</td>
      <td>6</td>
      <td>1</td>
    </tr>
    <tr>
      <td>decreases^mutagenesis</td>
      <td>6</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^palmitoylation</td>
      <td>6</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^glycation</td>
      <td>4</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^N-linked glycosylation</td>
      <td>3</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>decreases^carbamoylation</td>
      <td>3</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>affects^glutathionylation</td>
      <td>3</td>
      <td>0</td>
    </tr>
    <tr>
      <td>decreases^O-linked glycosylation</td>
      <td>3</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>Myristoylation</td>
      <td>2</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^lipidation</td>
      <td>2</td>
      <td>0</td>
    </tr>
    <tr>
      <td>affects^alkylation</td>
      <td>2</td>
      <td>0</td>
    </tr>
    <tr>
      <td>affects^farnesylation</td>
      <td>2</td>
      <td>0</td>
    </tr>
    <tr>
      <td>affects^N-linked glycosylation</td>
      <td>2</td>
      <td>0</td>
    </tr>
    <tr>
      <td>affects^carboxylation</td>
      <td>2</td>
      <td>0</td>
    </tr>
    <tr>
      <td>Depalmitoylation</td>
      <td>2</td>
      <td>-1</td>
    </tr>
    <tr>
      <td>Farnesylation</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <td>affects^glycation</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <td>decreases^acylation</td>
      <td>1</td>
      <td>-1</td>
    </tr>
  </tbody>
</table>
<p class="auto-cursor-target">
  <br/>
</p>

**Comment by djinnome** [comment]
I will follow the intact.py example by converting this table to this format:

| Source Type | Target Type | Interaction Type                                                     | BEL Example                                                 |
|-------------|-------------|----------------------------------------------------------------------|-------------------------------------------------------------|
| Protein     | Protein     | psi-mi:"MI:0193"(amidation reaction)                                 | p('uniprot', 'P62865') increases p('uniprot', 'P10731')     |
| Protein     | Protein     | psi-mi:"MI:1327"(sulfurtransfer reaction)                            | p('uniprot', 'Q46925') increases p('uniprot', 'P0AGF2')     |
| Protein     | Protein     | psi-mi:"MI:0945"(oxidoreductase activity electron transfer reaction) | p('uniprot', 'P0A3E0') increases p('uniprot', 'P21890')     |
| Protein     | Protein     | psi-mi:"MI:0217"(phosphorylation reaction)                           | p('uniprot', 'P53999') increases p('uniprot', 'P68400')     |

**Comment by cthoyt** [comment]
So after further investigation I think we're agreeing that Blender is just repackaging CTD, which we can get from INDRA. I'm going to close this issue
